"use strict";
let myFavourities = ["BMW Sedan", "Dark Sea Blue ", "Train", "Suzuki 150 Motorcycle",];
let myCar = "My favourite car is";
let color = "color should be";
let motbike1 = "My favourite bike is ";
let motbike2 = "beacause of its suspansion and speed";
let longdistance = "for long distance travel I preffer";
console.log(`${myCar} ${myFavourities[0]}`);
console.log(`${color} ${myFavourities[1]}`);
console.log(`${motbike1} ${myFavourities[3]} ${motbike2}`);
console.log(`${longdistance} ${myFavourities[2]}`);
