"use strict";
let myFavplaces = ["Madina", "MAkkah", "Kashmir", "Bosan", "Amazon", "Lasbela",];
console.log(myFavplaces);
const myFavplaces2 = myFavplaces.slice(0);
myFavplaces2.sort();
console.log(myFavplaces2);
console.log(myFavplaces);
const myFavplaces3 = myFavplaces.slice(0);
myFavplaces3.reverse();
console.log(myFavplaces3);
console.log(myFavplaces);
myFavplaces.reverse();
console.log(myFavplaces);
myFavplaces.reverse();
console.log(myFavplaces);
const myFavplaces4 = myFavplaces.slice(0);
myFavplaces4.sort();
console.log(myFavplaces4);
myFavplaces4.reverse();
console.log(myFavplaces4);
