"use strict";
let newGuestList = ['Shakir bhai', 'Shahzad', 'Imran Bhai', 'Sheheryar', 'Ejaz Abbasi'];
newGuestList.push("Wahab");
newGuestList.unshift("affan");
newGuestList.splice(3, 0, "sabir");
console.log(newGuestList);
console.log(`Asalam o Alaikum ${newGuestList[0]}  you are invited for dinner tonight at avari tower`);
console.log(`Asalam o Alaikum ${newGuestList[1]}  you are invited for dinner tonight at avari tower`);
console.log(`Asalam o Alaikum ${newGuestList[2]}  you are invited for dinner tonight at avari tower`);
console.log(`Asalam o Alaikum ${newGuestList[3]}  you are invited for dinner tonight at avari tower`);
console.log(`Asalam o Alaikum ${newGuestList[4]}  you are invited for dinner tonight at avari tower`);
console.log(`Asalam o Alaikum ${newGuestList[5]}  you are invited for dinner tonight at avari tower`);
console.log(`Asalam o Alaikum ${newGuestList[6]}  you are invited for dinner tonight at avari tower`);
console.log(`Asalam o Alaikum ${newGuestList[7]}  you are invited for dinner tonight at avari tower`);
